### ISSUE TITLE
CJK Test runs on a Latin font because of an orphan Korean glyph

### ISSUE THREAD

**Issue by alexeiva** [fonttools/fontbakery#3203] opened 2021-03-16 15:28 UTC
## Observed behaviour

```
com.google.fonts/check/cjk_vertical_metrics
🔥 FAIL OS/2 fsSelection bit 7 must be disabled [code: bad-fselection-bit7]
🔥 FAIL OS/2.sTypoAscender is "950" it should be 880.0 [code: bad-OS/2.sTypoAscender]
🔥 FAIL OS/2.sTypoDescender is "-250" it should be -120.0 [code: bad-OS/2.sTypoDescender]
🔥 FAIL hhea.ascent must match OS/2.usWinAscent [code: ascent-mismatch]
🔥 FAIL hhea.descent must match absolute value of OS/2.usWinDescent [code: descent-mismatch]
```
## Expected behaviour

I suspect the CJK Test fired up because of a single Korean symbol in the font `U+237F`

## Resources and exact process needed to replicate

https://github.com/googlefonts/youtube-kids/issues/12

**Comment by m4rc1e** [comment] 2021-03-16 15:30
Duplicate of #3164

**Closed** 2024-01-19 12:28 UTC
