### ISSUE TITLE
Add Check: nameID 17 should not be included in variable fonts (possibly should be limited to mac Platform nameIDs?)

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fontbakery#3282] opened 2021-05-13 20:19 UTC
## Observed behavior

If nameID 17 is present in a variable font, it can mess up the font style menu in macOS Catalina – showing nameID 17 many times for styles other than the one indicated, rather than the correct style names as pointed to in the `fvar` table.

[Recursive, for one, has had a terrible style menu for ages](https://github.com/arrowtype/recursive/issues/316), and this always perplexed me ... but this seems to solve it. I also found this to be a solution for a very similar problem on another font I am currently working on. I got the idea because Inter has the same axes as the new font, but Inter works just fine. Turns out, Inter leaves out name 17.

NameID 16, meanwhile, is still useful to keep, as leaving it out can negatively affect the font family name in the family menu.

So, nameID 16 is `Recursive`, and needs to stay this way, or the family menu will show nameID 1, `Recursive Sans Linear Light` (the name of the base instance, for non-variable environments). Name 17 was `Sans Linear Light`, and this was what was polluting my style menu in weird ways.

## Expected behavior

The font style menu should list each instance of a variable font exactly once.

## Resources and exact process needed to replicate

The problem exists in [Recursive VF 1.078](https://github.com/arrowtype/recursive/blob/728ced98fe7acc4756388fc937af43e61012d838/fonts/ArrowType-Recursive-1.078/Recursive_Desktop/Recursive_VF_1.078.ttf). If you remove name 17, this fixes it.

## Nuance / potential tradeoffs

Adam Twardoch pointed out a few nuances:

> But removing name ID 17 for 3.1 may have bad results on non-variable environments, like in older Adobe apps & various other apps
> 
> Adobe apps, apps like Corel Draw which support VFs, and apps like Affinity that don't, they show typographic family grouping so they use 16 & 17
> 
> also on Windows if a font has 16 but no 17 then an app would most likely use 16 for family name and 2 for style name
> 
> in your case "Recursive" + "Regular" ... which is not the default instance then

So, this recommendation offers a trade-off ... it might make a font work better on macOS Catalina, but slightly worse on apps/platforms that don’t handle variable fonts at all.

**Comment by arrowtype** [comment] 2021-05-13 20:46
Incidentally, if anyone needs the FontTools incantation to remove name 17 from a VF, here’s one:

```py
from fontTools.ttLib import TTFont


def main():
    args = parser.parse_args()
    # open font path as a font object, for manipulation

    fontPath = args.fontPath[0]
    font = TTFont(fontPath)

    # find nameID 17 and delete it
    for name in font['name'].names:
        if name.nameID == 17:
            font['name'].names.remove(name)

    # SAVE FONT
    if args.inplace:
        font.save(fontPath)
    else:
        try:
            font.save(fontPath.replace(".ttf",f".edit.ttf"))
        except:
            font.save(fontPath.replace(".otf",f".edit.otf"))


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Report what Unicode values a font includes *beyond* given Unicode ranges.')
    parser.add_argument('fontPath', 
                        help='Path to a variable font file',
                        nargs=1)
    parser.add_argument(
        "-i",
        "--inplace",
        action='store_true',
        help="Edit fonts and save under the same filepath, without an added suffix.",
    ) 

    main()
```

**Comment by arrowtype** [comment] 2021-05-14 01:50
Oh, but this problem doesn’t exist in macOS Big Sur. So, between that and the points from Adam, I think it only makes sense to remove name 17 if it is “Regular” – if you care about supporting macOS pre-11. I'm honestly unsure how relevant that is... it probably varies from family to family.


![image](https://user-images.githubusercontent.com/45946693/118208625-1ac02b00-b435-11eb-87af-8b6574008ee7.jpeg)

**Comment by RosaWagner** [comment] 2023-03-16 10:49
Usually if the actual style name is Regular/Bod/Italic/BoldItalic, there is no nameID 16 and 17 cause they would be duplicate of name ID 1 and 2. So I think this can be close.

**Closed** 2024-04-24 22:46 UTC
Labels: New check proposal
