### ISSUE TITLE
[com.google.fonts/check/license/OFL_body_text] Check should allow new OFL homepage

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4412] opened 2024-01-10 20:39 UTC
In `OFL_BODY_TEXT`, change `https://scripts.sil.org/OFL` to https://openfontlicense.org/
(Similarly in `PLACEHOLDER_LICENSING_TEXT`.)

(See https://github.com/google/fonts/pull/7104#issuecomment-1855608264)

**Comment by felipesanches** [comment] 2024-01-11 23:25
Both old and new URLs should be accepted. Perhaps the old one could cause a WARN.

**Comment by felipesanches** [comment] 2024-01-11 23:26
This is a duplicate of #4358

**Closed by felipesanches** 2024-01-11 23:26 UTC
Labels: Check improvement proposal
