### ISSUE TITLE
[spacing-mark-glyphs] suggests u+09CD is a spacing character

### ISSUE THREAD

**Issue by mitradranirban** [fonttools/fontbakery#4805] opened 2024-08-01 14:44 UTC
(**NOTE:** Please include the check-id in the issue's title.)

## Observed behaviour

**WARN** <p>The following spacing glyphs may be in the GDEF mark glyph class by mistake:
u09cd (U+09CD)</p>

## Expected behaviour

U+09CD Benngali Sign Virama should be classified as a mark for its proper positioning with Ligature by GPOS table blwm - so there should not be any such warning 

## Resources and steps needed to reproduce

 Font: Dakkhinee ( under production- UFO 
[Uploading Dakkhinee-Regular.ufo.zip…]()
file attached )
Font Bakery Version 0.12.9
Python (venv) version   Python 3.10.12
OS UBUNTU 22.04 LTS

**Comment by felipesanches** [comment] 2024-09-20 13:12
This is a duplicate of #4824 and a fix was released on FontBakery v0.13.0a1

**Closed by felipesanches** 2024-09-20 13:12 UTC
Labels: Check improvement proposal
