### ISSUE TITLE
com_google_fonts_check_074: Why must name ID 0 (copyright) be ASCII only?

### ISSUE THREAD

**Issue by m4rc1e** [fonttools/fontbakery#1718] opened 2018-02-19 10:52 UTC
In the Ms name table spec, https://docs.microsoft.com/en-gb/typography/opentype/spec/name#enc1 I see no mention of nameID 0 needing to be ASCII.

Imo, there's nothing wrong with having genuine copyright, tm and registered symbols. As long as the characters are within the Mac Roman encoding, https://en.wikipedia.org/wiki/Mac_OS_Roman for Mac entries and the BMP plane for Win entries, I don't think we're violating anything.

The reason I'm bringing this up is because Plex has the following copyright.
```
© 2017 IBM Corp. All rights reserved.
```

Am I missing something?

**Comment by m4rc1e** [comment] 2018-02-19 10:54
This issue also applies to [com_google_fonts_check_019](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/googlefonts.py#L646-L666). These symbols don't cause any issues.

**Comment by anthrotype** [comment] 2018-02-19 11:13
FYI there's been discussions on the OpenType mailing list on the fact that Macintosh names are no longer needed. Adobe apparently has been shipping fonts without them for some time.
http://www.indx.co.uk/biglistarchive/?mode=showpost&id=vbTjEt29gdc9ypGikFbivSkAP

**Comment by davelab6** [comment] 2018-02-19 17:13
The issue is that in cff table there is a copyright notice string that must
be ascii, and I want the same string everywhere.

**Comment by felipesanches** [comment] 2018-02-19 18:03
Is there a practical reason why you want it that way, Dave?

**Comment by m4rc1e** [comment] 2018-02-19 18:06
Thanks @anthrotype 

@davelab6 just checked the .otfs of IBM Plex and they're the same as the ttfs.

```
© 2017 IBM Corp. All rights reserved.
```

After reading the spec, I believe that TTFs and CFFs have the same name table and many other tables for that matter. The only real diffs between the formats are the 'CFF ' table in CFF fonts and 'glyf' in TTF fonts.

I agree that if we release CFF fonts, their name table's should match their TTF siblings.

**Comment by felipesanches** [comment] 2018-02-19 18:30
Should we keep the ASCII-only requirement then? If so, would you like to add some explanation on the rationale metadata field before closing this issue?

**Comment by davelab6** [comment] 2018-02-19 19:37
Are the cff with the non ascii character valid?

**Comment by m4rc1e** [comment] 2018-02-20 16:40
Yep, they're fine.

**Comment by davelab6** [comment] 2018-02-21 01:20
Oh. Then this issue should be to

- [ ] remove the copyright nameID from the `com_google_fonts_check_074` check

**Comment by anthrotype** [comment] 2018-02-21 11:25
> Are the cff with the non ascii character valid?

I couldn't find anything in the CFF specification, nor in the Type 1, nor in the PostScript one, about what is the encoding of these Copyright and Notice strings in the CFF TopDict.

In fontTools.cffLib they are read/written as "latin1" (which is a super-set of ascii, and does include "@" symbol).

https://github.com/fonttools/fonttools/blob/d46d40dc9e1811d47dab07920ced6aeac9068586/Lib/fontTools/cffLib/__init__.py#L1787-L1788

However in ufo2ft (originally ufo2fdk) we drop all non-ascii characters plus some special characters which are invalid in the context of a postscript string like `[](){}<>/%`

https://github.com/googlei18n/ufo2ft/blob/0cf1aa3d8bff4ef062fb4c2261106957bffa77dd/Lib/ufo2ft/fontInfoData.py#L196-L215

Maybe @readroberts could tell more?

**Comment by m4rc1e** [comment] 2018-02-21 11:54
@anthrotype Thank you for taking the time to explain this.

I'm not sure we'll ever release type 1 fonts. However, it may be best to stick with what we've got.

I see we've already had a heated discussion on this test, https://github.com/googlefonts/fontbakery/issues/1663

**Comment by anthrotype** [comment] 2018-02-21 12:04
> I'm not sure we'll ever release type 1 fonts

of course not. I mentioned Type1 because the CFF spec refers to that for the meaning of those TopDict operators. The text encoding is still unclear, but ascii is indeed the safest bet for CFF strings. What you're mostly interested in is not that it doesn't display garbage, because those strings are dead weight and they will never be seen by human beings -- unless one opens up the font in a hex editor or decompiles it with ttx, or perhaps if the CFF font is embedded in a PDF (not sure). It's the name table strings the ones the user will be shown.
What you're interested in is that the rest of the CFF table isn't rejected because of those useless piece of strings.

**Comment by felipesanches** [comment] 2018-02-21 13:43
> What you're interested in is that the rest of the CFF table isn't rejected because of those useless pieces of string.

I guess this can probably be the most important insight we've got in this conversation! Thanks for bringing this up, @anthrotype !

If that's really the major reason for us avoiding non-ASCII strings on some of the name table entries (such as copyright), then it may be good to mention that in the check rationale metadata field. Can anyone acknowledge that this is indeed the case? 

Also, it would be good to have a precise but succinct way of expressing that on the rationale text for **check/074** - `"Are there non-ASCII characters in ASCII-only NAME table entries?"`.

The rationale metadata field currently reads like this:

    The OpenType spec requires ASCII for the POSTSCRIPT_NAME (nameID 6).
    For COPYRIGHT_NOTICE (nameID 0) ASCII is required because that
    string should be the same in CFF fonts which also have this
    requirement in the OpenType spec.
    
    Note:
    A common place where we find non-ASCII strings is on name table
    entries with NameID > 18, which are expressly for localising
    the ASCII-only IDs into Hindi / Arabic / etc.

**Comment by anthrotype** [comment] 2018-02-21 13:47
Or maybe you could relax the requirement that the nameID 0 be _exactly_ equal to CFF Copyright string..

**Comment by readroberts** [comment] 2018-02-21 17:09
When CFF data is present as a CFF table in an OpenType font, there is a bunch of CFF data which is not relevant, and should be ignored in favor of the equivalent data in other tables - see the differences between the CFF2 and CFF table definitions. The CFF Copyright should be ignored, and certainly can be different than name table ID 1 - Adobe uses '@' in name id 0, but not in the CFF Copyright string.  The specification of the encoding of a copyright string in CFF is indeed poorly specified. The PostScript Language Reference Manual says that the 'Notice' field is a 'string' type, and then in section 3.3.7, says the encoding is unspecified and is whatever you want - the only limitation stated is that to enhance portability for strings that are present literally in the data, is charset can be limited to ASCII, but I haven't seen a tool that will reject a font for any encoding in the 'string' fields. I now recommend omitting the Notice or Copyright field from the CFF table.

**Comment by anthrotype** [comment] 2018-02-21 17:31
Thank you Read!

**Comment by tphinney** [comment] 2023-12-15 22:12
Regardless of what Read most recently recommended for new fonts, AFAIK Adobe has continuously released OpenType CFF fonts from at least **2000 to very recently**, with the copyright symbol. Back in the day it was a requirement for every Adobe font.

Here is Minion Pro from early OpenType releases
    <namerecord nameID="0" platformID="1" platEncID="0" langID="0x0" unicode="True">
      © 2000, 2002 Adobe Systems Incorporated. All Rights Reserved. U.S. Patent Des. 337,604. Other patents pending.

Here is the Minion Variable Concept released around the time of Read’s comment
    <namerecord nameID="293" platformID="1" platEncID="0" langID="0x0" unicode="True">
      MinionConceptRoman-DisplayBold
    </namerecord>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      © 1990-2018 Adobe. All rights reserved.

**Comment by rimas-kudelis** [comment] 2024-09-30 13:08
Please reconsider this requirement. Type 1 fonts are ancient history now, and the copyright field in the CFF table is just a legacy placeholder. Why limit font authors to ASCII when there's no practical need for that?

**Comment by rimas-kudelis** [comment] 2024-10-22 18:06
Is there any chance that a PR relaxing these non-ASCII checks of questionable value be accepted?

OpenType spec only requires `NameID`s 6, 20, and 25 to translate to ASCII, and there's no clear evidence that other `NameID`s need that (see https://github.com/fonttools/fontbakery/issues/1718#issuecomment-367398623 and #2854).

**Comment by rimas-kudelis** [comment] 2024-10-22 20:24
Since it's not that much work, I figured I'll just try my luck.

**Comment by davelab6** [comment] 2024-10-23 07:01
Thanks @rimas-kudelis and @readroberts for explaining. I agree to change this now that we don't expect any users to convert CFF to Type1.

**Closed by davelab6** 2024-10-23 07:01 UTC
Labels: P2 Important
