### ISSUE TITLE
Re-evaluate the best strategy for dealing with checks that validade the coherence between METADATA.pb and data on the font binaries

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#2216] opened 2018-11-22 03:22 UTC
On #2210 a reasonable request was made: that both METADATA.pb and name table values should be validated by the same check. That issue in particular refered to the expected copyright notice strings, but the same could be true about other checks of METADATA.pb values that need to be coherent with the contents of the font binaries.

Our current approach up to now was to have complementary checks that performed the same validation on different places. For instance, one check could enforce the string format on METADATA.pb while another check would simply expect the value to be equal (without explicitly re-validating the strings).

Another approach would be what we just did on #2210.

One problem, though, is that `font_metadata` is a condition for running those METADATA.pb specific checks and that means most upstream font-projects won't run those checks at all. So I think in that case we should make font_metadata optional, but emit a WARN.

Because of it, this approach could end up complicating the codebase, so we should be careful before going that route.

**Comment by davelab6** [comment] 2020-06-29 19:41
in https://github.com/googlefonts/gftools/issues/200#issuecomment-631513002 I wrote,

> @graphicore and @m4rc1e I just had a video call about this; we resolved that there are dozens of metadata checks in the gf profile that need to be refactored, as there appears to be a lot of redundancy, and Lasse will do this along with refactoring other parts of the gf profile, and the underlying fontbakery core code, related to super/sibling families, in June.

Seems this was a duplicate of this issue, so bumping to P0 priority

**Comment by felipesanches** [comment] 2020-06-29 20:56
yes, indeed! Thanks, Dave

**Comment by davelab6** [comment] 2020-06-29 20:58
Generally, the metadata files need to be accurate to what is in the font,
so if the fonts have X and the METADATA file has Y, we should prefer X.

>

**Comment by felipesanches** [comment] 2020-06-29 21:04
Also, `METADATA.pb` checks are 100% specific to the gfonts profile, while the corresponding checks for font binary data may be generaly useful on other profiles (ideally `universal`).

So having font binary data as the "source of truth" and keeping separate checks for binaries and metadata, would seem to be the way to go, in my opinion.

Does it change the perception of there being lots of redundancy? Or are there any other aspects to such redundancy you've been discussing in that meeting?

**Comment by felipesanches** [comment] 2021-09-02 11:53
I've just assigned this to @m4rc1e because it seems to be an issue closely coupled to his work on refactoring name table checks, as seen at #3404

**Comment by simoncozens** [comment] 2024-01-22 09:04
I don't think we should do this; we want to be able to check the name entries regardless of the presence or absence of a METADATA.pb file, so the check should be independent. If anything we want to coalesce checks which touch the same file (i.e. do all the METADATA.pb things at once instead of loading/parsing it multiple times) rather than coalesce across files which may or may not be present.

**Closed by simoncozens** 2024-01-22 09:04 UTC
Labels: P0 Urgent
