### ISSUE TITLE
JSONDecodeError on multiple checks

### ISSUE THREAD

**Issue by DavidRaymond** [fonttools/fontbakery#3658] opened 2022-03-16 15:59 UTC
I've started getting ERRORs on various checks.  I've reproduced using:

```fontbakery check-googlefonts data/test/cabin/Cabin-Bold.ttf --checkid=com.google.fonts/check/vertical_metrics_regressions```

which gives:

```         ERROR The condition                                                         
          <FontBakeryCondition:regular_remote_style> had an error:              
          FailedConditionError: The condition  
          <FontBakeryCondition:remote_styles> had an error: JSONDecodeError:    
          Expecting value: line 1 column 1 (char 0)                             
          ↳ File                                                                
          "/usr/local/lib/python3.8/dist-packages/fontbakery/checkrunner.py",   
          line 220, in _evaluate_condition                                      
          args = self._get_args(condition, iterargs, path)                      
          ↳ File                                                                
          "/usr/local/lib/python3.8/dist-packages/fontbakery/checkrunner.py",   
          line 359, in _get_args                                                
          args[name] = self._get(name, iterargs, path)                          
          ↳ File                                                                
          "/usr/local/lib/python3.8/dist-packages/fontbakery/checkrunner.py",   
          line 330, in _get                                                     
          raise error
```
Font Bakery version 0.8.8.dev26+g15022a66 on Ubuntu 20.04.

**Comment by m4rc1e** [comment] 2022-03-16 16:05
We had the same issue in gftools, https://github.com/googlefonts/gftools/issues/518

Appears our backend api endpoints have changed.

**Comment by felipesanches** [comment] 2022-03-16 19:07
Duplicate of https://github.com/googlefonts/fontbakery/issues/3661, fixed at https://github.com/googlefonts/fontbakery/pull/3662

**Closed as completed by felipesanches** 2022-03-16 19:07 UTC
