### ISSUE TITLE
[com.google.fonts/check/mandatory_glyphs] [code: empty] empty .notdef should FAIL instead of WARN

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#3958] opened 2022-11-23 09:47 UTC
## Observed behaviour

WARNS tend to be ignored, and an empty .notdef shouldn't be ignored imo. Users may not notice a glyphs is missing if the .notdef is a space, particularly for users who are not familiar with the content for which they make a website etc. 

⚠ WARN: Font contains '.notdef' as its first glyph? ([com.google.fonts/check/mandatory_glyphs](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs))
⚠ WARN Glyph '.notdef' should contain a drawing, but it is empty. [code: empty]

## Expected behaviour

Missing glyphs in font must be obvious, so I would propose to make it a FAIL instead of a WARN, for the Google Fonts profile at least.

@vv-monsalve @yanone @m4rc1e @davelab6 do you agree? thumbs up if yes.

**Comment by simoncozens** [comment] 2023-10-11 11:47
This is a duplicate of #4093, and I fixed it in #4236.

**Closed by simoncozens** 2023-10-11 11:47 UTC
Labels: Severity 3, Profile: Google Fonts, Check-result level revision, GF's priority list
